# permissions for end users to view abstractworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: abstractworkload-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: abstract-workload
    app.kubernetes.io/part-of: abstract-workload
    app.kubernetes.io/managed-by: kustomize
  name: abstractworkload-viewer-role
rules:
- apiGroups:
  - examples.mvasilenko.me
  resources:
  - abstractworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - examples.mvasilenko.me
  resources:
  - abstractworkloads/status
  verbs:
  - get
