---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - examples.mvasilenko.me
  resources:
  - abstractworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - examples.mvasilenko.me
  resources:
  - abstractworkloads/finalizers
  verbs:
  - update
- apiGroups:
  - examples.mvasilenko.me
  resources:
  - abstractworkloads/status
  verbs:
  - get
  - patch
  - update
